waypoints:
  - id: p1_0
    x: -0.5855
    y: -0.0422
    yaw: 0.0
    children: [p1_1]

  - id: p1_1
    x: -2.0103
    y: -0.0105
    yaw: 0.0
    children: [p1_2]

  - id: p1_2
    x: -2.9338
    y: 0.0147
    yaw: 0.0
    children: []
