waypoints:
  - id: elevator
    x: 0.655668
    y: -2.09866
    yaw: 3.14
  - id: waypoint1
    x: -0.84104
    y: -2.62785
    yaw: 0.0
  - id: point1
    x: -2.00275
    y: -2.02759
    yaw: 0.0
  - id: waypoint2
    x: -0.44531
    y: -0.94534
    yaw: 0.0
  - id: point2
    x: -1.784
    y: -0.572
    yaw: 0.0