waypoints:
  - id: p1_0
    x: -0.5855
    y: -0.0422
    yaw: 0.0
    neighbors: [p1_1]

  - id: p1_1
    x: -2.0103
    y: -0.0105
    yaw: 0.0
    neighbors: [p1_0, p1_2]

  - id: p1_2
    x: -2.9338
    y: 0.0147
    yaw: 0.0
    neighbors: [p1_1, p2_0]

  - id: p2_0
    x: -0.5855
    y: -0.0422
    yaw: 0.0
    neighbors: [p1_2, p2_1, p2_3]

  - id: p2_1
    x: -2.0103
    y: -0.0105
    yaw: 0.0
    neighbors: [p2_0, p2_2]

  - id: p2_2
    x: -2.9338
    y: 0.0147
    yaw: 0.0
    neighbors: [p2_1, p2_4]

  - id: p2_3
    x: -2.0103
    y: -0.0105
    yaw: 0.0
    neighbors: [p2_0, p2_4]

  - id: p2_4
    x: -2.9338
    y: 0.0147
    yaw: 0.0
    neighbors: [p2_2, p2_3]
